### PR TITLE
feature: wait until albion process is found before invoking systray

### PR DESCRIPTION
**Pull request by Icaruk**
Hi! This is my first contribution.

I modified `systray\systray_win.go` to wait until albion process is found. Here is the summary:

- I added https://github.com/shirou/gopsutil
- Added `findAlbionProcess` function.
- Added `targetProcessName` constant.
- Added `albionProcessTimeBetweenChecks` constant.
- In the `onReady` function, I invoked `findAlbionProcess` on the very top of the function, blocking execution until process is found.

This could prevent https://github.com/ao-data/albiondata-client/issues/84#issuecomment-2088330768

I added 2 new info messages. I don't know if I should remove them.

- "Waiting for Albion to start..."
- "Albion is running."

image

I built the 3 binaries (windows, linux, darwin) without any errors.

I need help with:
- The formatter automatically adds `//go:build windows` on the  `systray\systray_win.go` file.
- I don't know if this is the right spot to wait until albion process is running.
- In `go.mod` there is a `github.com/shirou/gopsutil v3.21.11+incompatible // indirect` and I don't know if it's something bad.

### CODE REVIEW

**Comment by phendryx** [comment]
I'm not sure I agree with the idea of "Gets all processes periodically and stops when albion is found running". What happens when a user closes and reopens the game? I have not tested it, it does need to be tested on each OS and it might be fine if all this is for is adding the icon to the systray, which is windows only I believe, but that leads to the next issue.

There's also a lot of module changes. I'm not that familiar with golang despite running this project. I know what I need to change when I have to update certain things. I don't know a lot past that and that makes me uncomfortable doing big changes. But overall, I don't think the answer is swapping out a bunch of modules and putting a timer in place. I think the issue here is literally the application is trying to start too early after reboot and that we need to add a shortcut to the startup folder vs the task scheduler.

By no means am I rejecting this, I'm just stating my concerns/thoughts.

**Comment by Icaruk** [comment]
Thank you for your time @phendryx 

> I'm not sure I agree with the idea of "Gets all processes periodically and stops when albion is found running".

I've been researching and haven't found a way to get a process by name without iterating over all running ones. :(

> What happens when a user closes and reopens the game?

Nothing, the systray is already executed.

> There's also a lot of module changes.

- Removed https://github.com/shirou/gopsutil (replaced by `golang.org/x/sys/windows`)
- Reverted unintentional dependencies update (I executed `go get -u ...` instead `go get ...`)

> I think the issue here is literally the application is trying to start too early after reboot and that we need to add a shortcut to the startup folder vs the task scheduler.

I'm sorry, with the knowledge I have at the moment, this is the only thing I can do.

---

I need help with:

- Maybe should I move the blocking `findAlbionProcess` from `onReady` to `Run` on the `systray\systray_win.go` file?
- The formatter automatically adds //go:build windows on the systray\systray_win.go file.

**Comment by Icaruk** [comment]
@phendryx Any news on this?

**Comment by phendryx** [comment]
I don't think this is going to get included, at least not as is. I disagreed with it in May. I still disagree with it now. If someone closes the game and then reopens it, I don't think this code would work and no data would be captured after the initial game run.

The issue that drive this was sometimes this runs before network adapters are properly initialized. The solve here is not addressing the issue, it's assuming something else entirely; "the game isn't running yet" which doesn't actually matter.

**Comment by Icaruk** [comment]
> I don't think this is going to get included, at least not as is. I disagreed with it in May. I still disagree with it now. If someone closes the game and then reopens it, I don't think this code would work and no data would be captured after the initial game run.
> 
> The issue that drove this was sometimes this runs before network adapters are properly initialized. The solve here is not addressing the issue, it's assuming something else entirely; "the game isn't running yet" which doesn't actually matter.

Thanks, I totally understand that.
I'll try to find a way to do it properly, to re-open this.
Thanks!

**Pull request closed without merging**
